[workspace]
resolver = "2"
members = [
	"cvlr-vectors",
]

[workspace.package]
version = "0.3.0"
authors = ["Certora"]
description = "Certora Verification Language for Rust"
documentation = "https://certora.com"

[workspace.dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
macrotest = "1"
trybuild = "1"

cvlr-asserts = { git = "https://github.com/1arie1/cvlr.git", version = "0.4" }
cvlr-nondet = { git = "https://github.com/1arie1/cvlr.git", version = "0.4" }
